
server:
  port: 8083

spring:
  application:
    name: ms-persistence
  data:
    mongodb:
      uri: mongodb://localhost:27017/payments

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
