server:
  port: 8080 # Define explícitamente el puerto para el orquestador

spring:
  application:
    name: temporal-orchestrator
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

temporal:
  connection:
    target: 127.0.0.1:7233
